=== Nested Steps

icon:check-square[role=green] 1 Successful, icon:exclamation-circle[role=red] 1 Failed, icon:ban[role=silver] 0 Pending, 2 Total (7ms)

// tag::scenario-failed[]

==== A scenario with a failing nested step on purpose

icon:exclamation-circle[role=red] (1ms)

Tags: _FailingOnPurpose_

[unstyled.jg-step-list]
* [.jg-intro-word]*Given* I fill out the registration form with invalid values icon:exclamation-circle[role=red] (1ms)

** I enter a name [.jg-argument]_Franky_ icon:check-square[role=green]

*** I think a name [.jg-argument]_Franky_ icon:check-square[role=green]

*** [.jg-intro-word]*And* I write the name [.jg-argument]_Franky_ icon:check-square[role=green]

** [.jg-intro-word]*And* I enter a email address [.jg-argument]_franky@acme.com_ icon:check-square[role=green]

** [.jg-intro-word]*And* something fails for demonstration purposes icon:exclamation-circle[role=red]

* [.jg-intro-word]*When* I submit the form icon:ban[role=silver]

* [.jg-intro-word]*Then* the password matches icon:ban[role=silver]

.org.opentest4j.AssertionFailedError: [Fails on purpose] 
[.jg-exception%collapsible]
====
Expecting value to be false but was true

....
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage.something_fails_for_demonstration_purposes(NestedStepsTest.java:72)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy.something_fails_for_demonstration_purposes$accessor$Zj6zME7c(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy$auxiliary$YA6YRU7S.call(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy.something_fails_for_demonstration_purposes(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage.I_fill_out_the_registration_form_with_invalid_values(NestedStepsTest.java:67)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy.I_fill_out_the_registration_form_with_invalid_values$accessor$Zj6zME7c(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy$auxiliary$rAwdzEwx.call(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest$NestedStage$ByteBuddy$LmQRfnWy.I_fill_out_the_registration_form_with_invalid_values(Unknown Source)
com.tngtech.jgiven.examples.nested.NestedStepsTest.a_scenario_with_a_failing_nested_step_on_purpose(NestedStepsTest.java:32)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
com.tngtech.jgiven.junit.JGivenMethodRule$1.evaluate(JGivenMethodRule.java:73)
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
org.junit.rules.RunRules.evaluate(RunRules.java:20)
org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
org.junit.runners.ParentRunner.run(ParentRunner.java:413)
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
....
====


// end::scenario-failed[]

// tag::scenario-successful[]

==== A scenario with nested steps

icon:check-square[role=green] (5ms)

+++This scenario contains nested steps.+++

[unstyled.jg-step-list]
* [.jg-intro-word]*Given* I fill out the registration form with valid values

** I enter a name [.jg-argument]_Franky_

*** I think a name [.jg-argument]_Franky_

*** [.jg-intro-word]*And* I write the name [.jg-argument]_Franky_

** [.jg-intro-word]*And* I enter a email address [.jg-argument]_franky@acme.com_

** [.jg-intro-word]*And* I enter a password [.jg-argument]_password1234_

** [.jg-intro-word]*And* I enter a repeated password [.jg-argument]_password1234_

* [.jg-intro-word]*When* I submit the form

* [.jg-intro-word]*Then* the password matches

// end::scenario-successful[]

